// /*
//  * This Java source file was generated by the Gradle 'init' task.
//  */
// package Search;

// <<<<<<< model
// // public class App {
// //     public String getGreeting() {
// //         return "Hello World!";
// //     }

// //     public static void main(String[] args) {
// //         System.out.println(new App().getGreeting());
// //     }
// // }
// =======
// import Search.Models.rbTree;
// import Search.Utils.JsonParsing;

// public class App {
//     public static void main(String[] args) {
//         rbTree<String, String> tree = new rbTree<>();
//         String resourcePath = "/data.json"; // Path file JSON di dalam folder resources
//         JsonParsing.loadJsonData(tree, resourcePath);
//     }
// }

// >>>>>>> main
