/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Search;

import Search.Models.rbTree;
import Search.Utils.JsonParsing;

public class App {
    public static void main(String[] args) {
        rbTree<String, String> tree = new rbTree<>();
        String resourcePath = "/data.json"; // Path file JSON di dalam folder resources
        JsonParsing.loadJsonData(tree, resourcePath);
    }
}

